version: "3"

services:
  api:
    container_name: api-fastfeet
    build: .
    command: yarn server
    ports:
      - 9000:9000
    volumes:
      - .:/usr/app/
    depends_on:
      - database
    networks:
      - app-network
  database:
    image: mysql:5.7
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fastfeet
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin-fastfeet
    ports:
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
